[bell]
duration = 0

[[colors.indexed_colors]]
color = "#f39967"
index = 16

[[colors.indexed_colors]]
color = "#efc9c2"
index = 17

[colors.bright]
black = "#505469"
blue = "#739df2"
cyan = "#78cec1"
green = "#96d382"
magenta = "#f2a7de"
red = "#ea7183"
white = "#959ec2"
yellow = "#eaca89"

[colors.cursor]
cursor = "#FFCC00"
text = "#727272"

[colors.dim]
black = "#3e4255"
blue = "#739df2"
cyan = "#78cec1"
green = "#96d382"
magenta = "#f2a7de"
red = "#ea7183"
white = "#a6b0d8"
yellow = "#ffcb6b"

[colors.hints.end]
background = "#a6b0d8"
foreground = "#1a1c2a"

[colors.hints.start]
background = "#eaca89"
foreground = "#1a1c2a"

[colors.normal]
black = "#3e4255"
blue = "#739df2"
cyan = "#78cec1"
green = "#96d382"
magenta = "#f2a7de"
red = "#ea7183"
white = "#a6b0d8"
yellow = "#eaca89"

[colors.primary]
background = "#1a1c2a"
bright_foreground = "#eeffff"
dim_foreground = "#eeffff"
foreground = "#eeffff"

[colors.search.focused_match]
background = "#96d382"
foreground = "#1a1c2a"

[colors.search.matches]
background = "#a6b0d8"
foreground = "#1a1c2a"

[colors.selection]
background = "#efc9c2"
text = "#1a1c2a"

[colors.vi_mode_cursor]
cursor = "#a0a8f6"
text = "#1a1c2a"

[env]
TERM = "alacritty"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.glyph_offset]
x = 0
y = 5

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
y = 10

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001BW"
key = "W"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Super"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Super"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Super"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Super"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[window]
decorations = "none"
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
